### ISSUE TITLE
Export names 

### ISSUE THREAD

**Issue by varazir** [WilkoV/Fusion360_FilteredExport#1]
Hello, 

I have created a drawing like this https://i.imgur.com/FdRDvjq.png 
I would love to have all componentnames in the name of the exported file

Nos I get example 
LACK_MK2-Bottom_Front_Left-Body1.stl
LACK_MK2-FrontCone-Body1.stl

Would like to it to be 

LACK_MK2-Corner-Bottom_Front_Left-Body1.stl
LACK_MK2-Corner-Bottom_Front_Left-FrontCone-Body1.stl

TIA
Daniel 

Btw have you created a new repo?

**Comment by WilkoV** [comment]
So you want basically the full tree structure in the name. I've to check this, but I guess this information is not collected by the plugin right now. Not sure if I can add this without rewriting everything. I'll come back later.

**Comment by WilkoV** [comment]
@varazir : I have a question.  This example ([Levels v6.zip](https://github.com/WilkoV/Fusion360_FilteredExport/files/2856629/Levels.v6.zip)) shows a project that has:

- a body in the root, 
- a component L1 that contains a body (L1:1)
- a component L1.2. inside of L1 (L1.2:1)
- a copy/past from the L1:1 (L1:2 containing another L1.2:1)
- a copy/past from the L1.2 component pasted to the root (L1.2:2)

The export will contain 3 stl files. One body from the L1:1 component, one body from the L1.2 component and one body from the root. All other components are identified as duplicated objects (and that's the hole reason of the plugin)

![example export](https://user-images.githubusercontent.com/17180350/52650635-ed4d4580-2eea-11e9-9512-0d709b14508b.png)

Right now the export names (with default configuration) are:
- Levels-L1-Body1
- Levels-L1,2-Body1
- Levels-Body1

What you want is:
- Levels-L1-Body1
- Levels-L1-L1.2-Body1
- Levels-Body1

Or do you want something like this:
- Levels-L1_1-Body1
- Levels-L1_1-L1.2_1--Body1
- Levels-L1_2-Body1
- Levels-L1_2-L1.2_1--Body1
- Levels-L1.2_2--Body1
- Levels-Body1

**Comment by varazir** [comment]
I want this 
* Levels-L1-Body1
* Levels-L1-L1.2-Body1
* Levels-Body1

Easier to find the body when you look at the STL file name

**Comment by varazir** [comment]
Maybe a option Flat( only the last component ) Full tree name.

**Comment by WilkoV** [comment]
Adding it to the menu is not the problem. Getting the needed data is that what I have to figure out without rewriting everything.

**Comment by WilkoV** [comment]
@varazir So, this should to the trick. I hope this is what you wanted.

**Comment by varazir** [comment]
> @varazir So, this should to the trick. I hope this is what you wanted.

Perfekt!
